# The name of the workflow. GitHub displays the names of your workflows under your repository's "Actions" tab. If you omit `name`, GitHub displays the workflow file path relative to the root of the repository.
name: CI

#
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#
jobs:
  build:
    permissions: write-all #for dependabot auto PR - create a test report
    # <!-- This is a YAML comment for use in annotated code examples. -->
    # You can run this workflow using a different operating systems.
    #
    # The starter workflow configures jobs to run on Linux, using the GitHub-hosted `ubuntu-latest` runners. You can change the `runs-on` key to run your jobs on a different operating system.
    #
    # For example, you can use the GitHub-hosted Windows runners by specifying `runs-on: windows-latest`. Or, you can run on the GitHub-hosted macOS runners using `runs-on: macos-latest`.
    #
    # You can also run jobs in Docker containers, or you can provide a self-hosted runner that runs on your own infrastructure. For more information, see "[AUTOTITLE](/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on)."
    runs-on: ubuntu-latest
    #
    steps:
      # This step uses the `actions/checkout` action to download a copy of your repository on the runner.
      - uses: actions/checkout@v4
      # This step uses the `actions/setup-java` action to configure the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build by Maven
        run: mvn clean install -DskipTests=true
      - name: run dev tests
        run: mvn test -Dspring.profiles.active=dev
      - name: reactive-service JUnit Test Report
        uses: dorny/test-reporter@v1.8.0 #{owner}/{repository}@{ref}
        if: (success() || failure())
        #        if: github.actor != 'dependabot[bot]' && (success() || failure())
        with:
          name: Tests - reactive-service #for analysis tests report
          path: /target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.github_token}}

      # Now you can pass ${{ steps.buildnumber.outputs.build_number }} to the next steps.
      - name: Another step as an example
        uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: ${{ steps.buildnumber.outputs.build_number }}
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
